# Generated by Django 5.2.12 on 2026-05-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WireLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(db_index=True, max_length=50)),
                ("sub_label", models.CharField(blank=True, max_length=50)),
                ("status", models.CharField(db_index=True, max_length=12)),
                ("data", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
